#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     HTCS2,          sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          right,         tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

#define FINDINGLINE 0
#define FOLLOWLINE 1
#define AVOIDLINE 2
int currentState = FINDINGLINE;
bool whiteToBlackCheck = false;

const int fasterSpeed = 20;
const int lowerSpeed = 3;
long baselineColourLine = 450;

long currentColour, r, g, b;

int leftMotorSpeedFind = fasterSpeed;
int rightMotorSpeedFind = lowerSpeed;

int leftMotorSpeedFollow;
int rightMotorSpeedFollow;

int leftMotorSpeedAvoid;
int rightMotorSpeedAvoid;
